/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

export interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/about/index" |
       "/pages/demo/index" |
       "/pages/demo/mp-weixin-share" |
       "/pages/demo/pinia" |
       "/pages/log/index" |
       "/pages/login/index" |
       "/pages/notFound/404" |
       "/pages/template/index" |
       "/pagesA/list/test1/index" |
       "/pagesA/list/test2/index" |
       "/pagesB/detail/index";
}
interface RedirectToOptions extends NavigateToOptions {}

export interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/demo/index" | "/pages/about/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
